function [fitresult, gof] = createFit13BR(xVals, yVals)
%CREATEFIT(XVALS,YVALS)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : xVals
%      Y Output: yVals
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 30-Sep-2025 08:44:26


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( xVals, yVals );

% Set up fittype and options.
ft = 'pchipinterp';

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, 'Normalize', 'on' );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'yVals vs. xVals', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'xVals', 'Interpreter', 'none' );
ylabel( 'yVals', 'Interpreter', 'none' );
grid on


