function [fitresult, gof] = createFit1(xVals, yVals)
%CREATEFIT1(XVALS,YVALS)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : xVals
%      Y Output: yVals
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 24-Sep-2025 15:30:07


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( xVals, yVals );

% Set up fittype and options.
ft = fittype( 'gauss3' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [-Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0];
opts.Normalize = 'on';
opts.StartPoint = [0.965316094462373 1.39833444681554 1.10838771456578 0.906395486454039 -0.749077781047559 0.278500191753607 0.81516912303964 -0.195448066051603 0.323451225972073];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'yVals vs. xVals', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'xVals', 'Interpreter', 'none' );
ylabel( 'yVals', 'Interpreter', 'none' );
grid on


