function [fitresult, gof] = createFit(xVals, yVals)
%CREATEFIT(XVALS,YVALS)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : xVals
%      Y Output: yVals
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 24-Sep-2025 15:25:03


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( xVals, yVals );

% Set up fittype and options.
ft = fittype( 'fourier2' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Normalize = 'on';
opts.StartPoint = [0 0 0 0 0 0.985577589233993];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'yVals vs. xVals', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'xVals', 'Interpreter', 'none' );
ylabel( 'yVals', 'Interpreter', 'none' );
grid on


