function [fitresult, gof] = createFit4(xVals, yVals)
%CREATEFIT(XVALS,YVALS)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : xVals
%      Y Output: yVals
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 25-Sep-2025 06:03:22


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( xVals, yVals );

% Set up fittype and options.
ft = fittype( 'gauss2' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [-Inf -Inf 0 -Inf -Inf 0];
opts.StartPoint = [0.806843121790192 30 13.4767687763946 0.642494796342146 3 9.40404987105038];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'yVals vs. xVals', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'xVals', 'Interpreter', 'none' );
ylabel( 'yVals', 'Interpreter', 'none' );
grid on


